service: tinfluence
provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    cors: true
functions:
  graphql:
    handler: app/server.handler
    events:
      - httpApi:
          path: /graphql
          method: POST
      - httpApi:
          path: /graphql
          method: GET
plugins:
  - serverless-plugin-typescript
  - serverless-offline
